// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxrywakpoknngagxobdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cnl3YWtwb2tubmdhZ3hvYmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjQ2NTEsImV4cCI6MjA2ODI0MDY1MX0.S-n3Lf3BEBbeUo5EgXoL56DW6FDt7_MEd0daPeG7BCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});